orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test72
      - test73
      - test74
      - test80
      - docs_build:
          requires:
            - lint
            - test72
            - test73
            - test74
            - test80
          filters:
            branches:
              only: master

jobs:
  lint:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - checkout
      - run: { name: "Install dependencies", command: sudo composer self-update && composer install -n --prefer-dist && mkdir --parents tools/php-cs-fixer && composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer }
      - run:
          name: Syntax tests
          command: |
             tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation -v
      - run:
          name: Static analysis
          command: |
            wget https://github.com/phpstan/phpstan/releases/download/0.10.3/phpstan.phar -q -O phpstan.phar
            composer run lint-static-analysis

  test72:
      environment:
          CC_TEST_REPORTER_ID: 8feb70b07f601a8af99f8d07d8a3531350ffcf3d73fb448d7d8e593bc53c9771
          XDEBUG_MODE: coverage
      docker:
      - image: circleci/php:7.2-cli
      steps:
      - checkout
      - run:
            name: Set up Code Climate test-reporter
            command: |
                curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                chmod +x ./cc-test-reporter
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run:
            name: Test suite
            command: |
                sudo docker-php-ext-enable xdebug
                ./cc-test-reporter before-build
                composer test-quick-fail
                ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

  test73:
      docker:
          - image: circleci/php:7.3-cli
      steps:
          - checkout
          - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
          - run: { name: "Test suite", command: "composer test-quick-fail" }
            
  test74:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - checkout
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

  test80:
    docker:
      - image: circleci/php:8.0-cli
    steps:
      - checkout
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }


  docs_build:
    environment:
      TRAVIS_REPO_SLUG: contentful/rich-text.php
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - checkout
      - run: {name: "Make docs", command: "sh ./scripts/prepare-docs.sh" }
      - gh-pages/deploy:
          build-dir: build/docs
          ssh-fingerprints: 88:17:70:03:64:ee:48:2d:c7:f9:c6:7b:ba:3a:d0:18
